# Generated by Django 5.1.7 on 2025-03-28 22:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problems', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='function',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='function',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.language'),
        ),
        migrations.AddField(
            model_name='executiontestcase',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_language', to='problems.language'),
        ),
        migrations.AddField(
            model_name='problem',
            name='category',
            field=models.ManyToManyField(related_name='problems_in_category', to='problems.categorys'),
        ),
        migrations.AddField(
            model_name='problem',
            name='language',
            field=models.ManyToManyField(related_name='problems_in_language', to='problems.language'),
        ),
        migrations.AddField(
            model_name='problem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='function',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='functions', to='problems.problem'),
        ),
        migrations.AddField(
            model_name='executiontestcase',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_problem', to='problems.problem'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_language', to='problems.language'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_problem', to='problems.problem'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='function',
            unique_together={('problem', 'language')},
        ),
        migrations.AlterUniqueTogether(
            name='executiontestcase',
            unique_together={('problem', 'language')},
        ),
        migrations.AlterUniqueTogether(
            name='testcase',
            unique_together={('problem', 'language', 'input_txt')},
        ),
    ]
