# Generated by Django 5.1.7 on 2025-03-27 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_problem', to='problems.problem'),
        ),
        migrations.AlterUniqueTogether(
            name='function',
            unique_together={('problem', 'language')},
        ),
    ]
