# Generated by Django 5.1.7 on 2025-04-03 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0002_initial"),
        ("problems", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="problem",
            name="lesson",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="lessons.lesson",
            ),
        ),
    ]
