# Generated by Django 5.1.7 on 2025-03-27 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_alter_testcase_problem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='input_txt',
            field=models.CharField(help_text='Test Input', max_length=250),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='output_txt',
            field=models.CharField(help_text='Chiqish Output', max_length=250),
        ),
    ]
