# Generated by Django 5.1.7 on 2025-04-03 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("problems", "0003_problem_lesson"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="testcase",
            unique_together=set(),
        ),
    ]
