# Generated by Django 5.1.7 on 2025-03-29 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="myuser",
            old_name="unsername",
            new_name="username",
        ),
    ]
