# Generated by Django 5.1.7 on 2025-04-03 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                default="profile/user/user.png",
                upload_to="profile/",
                verbose_name="Profil rasmi",
            ),
        ),
    ]
