# Generated by Django 5.1.7 on 2025-03-29 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='modules',
        ),
    ]
