# Generated by Django 5.1.7 on 2025-05-05 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizs', '0003_remove_question_content_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='bob',
            new_name='module',
        ),
        migrations.AlterField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='quizs.quiz'),
        ),
    ]
