# Generated by Django 5.1.7 on 2025-04-07 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('contest_type', models.CharField(choices=[('weekly', 'Haftalik Tanlov'), ('biweekly', '2-Haftalik Tanlov')], max_length=20)),
                ('contest_number', models.PositiveIntegerField(help_text='M: Bu hafta 345-chi haftalik tanlov')),
                ('start_time', models.DateTimeField()),
                ('duration', models.PositiveIntegerField(help_text='Daqiqalarda m: 90 daqiqa')),
                ('problem_count', models.PositiveIntegerField(default=4)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='UserContestStats',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='contest_stats', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('total_contests', models.PositiveIntegerField(default=0)),
                ('best_rank', models.PositiveIntegerField(blank=True, null=True)),
                ('average_rank', models.FloatField(blank=True, null=True)),
                ('total_points', models.PositiveIntegerField(default=0)),
                ('last_contest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contest.contest')),
            ],
            options={
                'verbose_name': 'User Contest Statistics',
                'verbose_name_plural': 'Users Contest Statistics',
            },
        ),
        migrations.CreateModel(
            name='ContestRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('is_participated', models.BooleanField(default=False)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('points', models.PositiveIntegerField(default=0)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_register', to='contest.contest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_contest_register', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'contest')},
            },
        ),
    ]
