# Generated by Django 5.1.7 on 2025-03-29 08:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("slug", models.SlugField(unique=True)),
            ],
            options={
                "verbose_name": "Teg",
                "verbose_name_plural": "Teglar",
            },
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Mavzu nomi")),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                ("description", models.TextField(verbose_name="Tavsif")),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Oson"),
                            ("medium", "Oʻrtacha"),
                            ("hard", "Qiyin"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("views", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Mavzu",
                "verbose_name_plural": "Mavzular",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TopicTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="contest.tag"
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topic_tags",
                        to="contest.topic",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mavzu Tegi",
                "verbose_name_plural": "Mavzu Teglari",
                "unique_together": {("topic", "tag")},
            },
        ),
    ]
