# Generated by Django 5.1.7 on 2025-04-12 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('contest_type', models.CharField(choices=[('weekly', 'Haftalik Tanlov'), ('biweekly', '2-Haftalik Tanlov')], max_length=20)),
                ('contest_number', models.PositiveIntegerField(help_text='M: Bu hafta 345-chi haftalik tanlov')),
                ('start_time', models.DateTimeField()),
                ('duration', models.PositiveIntegerField(help_text='Daqiqalarda m: 90 daqiqa')),
                ('problem_count', models.PositiveIntegerField(default=4)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='ContestRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('is_participated', models.BooleanField(default=False)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('points', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
