# Generated by Django 5.1.7 on 2025-04-03 08:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contest", "0001_initial"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="contestregistration",
            name="contest",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contest_register",
                to="contest.contest",
            ),
        ),
        migrations.AddField(
            model_name="contestregistration",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_contest_register",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="UserContestStats",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="contest_stats",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("total_contests", models.PositiveIntegerField(default=0)),
                ("best_rank", models.PositiveIntegerField(blank=True, null=True)),
                ("average_rank", models.FloatField(blank=True, null=True)),
                ("total_points", models.PositiveIntegerField(default=0)),
                (
                    "last_contest",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contest.contest",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Contest Statistics",
                "verbose_name_plural": "Users Contest Statistics",
            },
        ),
        migrations.AlterUniqueTogether(
            name="contestregistration",
            unique_together={("user", "contest")},
        ),
    ]
