# Generated by Django 5.1.7 on 2025-04-15 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userstatus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproblemstatus',
            name='date_completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
