# Generated by Django 5.1.7 on 2025-06-19 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userstatus', '0002_userproblemstatus_date_completed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='badge',
            options={'verbose_name': 'User Badge', 'verbose_name_plural': 'User Badge'},
        ),
    ]
